#!/bin/bash

set -e
set -x

/bin/s6-svwait -u /etc/s6/rclone

/bin/mkdir -p /mnt/local
/bin/mkdir -p /mnt/unionfs

/usr/bin/unionfs-fuse -f -o cow -o allow_other -o uid=$MOUNT_UID -o gid=$MOUNT_GID /mnt/local=RW:/mnt/rcache=RO /mnt/unionfs
